#!/usr/bin/env python3

'''
Michael Chen
2022-02-28

I have added the shebang as the first line of the file
so that it could be run in linux directly with the specified command
I have a windows machine so I couldn't test this for myself unfortunately.
There might still be issues when running this file beacuse there might be
format differences issues between files on windows and linux.
'''

import sys
from helpers import process_file, get_value_with_highest_key

# main function
def main():

    try:
        if len(sys.argv) != 4:
            raise SystemExit("Incorrect number of arguments.")

        filename = sys.argv[1]
        date = sys.argv[3] # this skips the -d part

        cookie_file = open(filename, 'r')

        same_occurences_sets, cookie_occurences_count = process_file(cookie_file, date)

        cookie_file.close()

        most_occurence_set = get_value_with_highest_key(same_occurences_sets)

        if most_occurence_set == None:
            print(f"No occurences were found for the date {date}")
        else:
            for cookie in most_occurence_set:
                print(cookie)

    except FileNotFoundError:
        print("File not found. Check the path variable and filename.")

        
main()


